// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

const TableNameDictionaryGroupItem = "dictionary_group_items"

// DictionaryGroupItem mapped from table <dictionary_group_items>
type DictionaryGroupItem struct {
	ID                int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt         time.Time      `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	DictionaryGroupID int64          `gorm:"column:dictionary_group_id;type:bigint" json:"dictionary_group_id"`
	Value             string         `gorm:"column:value;type:character varying(198);not null;comment:字典项值" json:"value"` // 字典项值
	Order             int64          `gorm:"column:order;type:bigint;not null;comment:排序" json:"order"`                   // 排序
}

func (*DictionaryGroupItem) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameDictionaryGroupItem
	}
	return namer.TableName(TableNameDictionaryGroupItem)
}
