// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/dictionary/modules/dictionary/controller"
	"github.com/atom-apps/dictionary/modules/dictionary/dto"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeDictionaryGroupItemController(engine fiber.Router, controller *controller.DictionaryGroupItemController) {
	basePath := "/"+engine.(*fiber.Group).Prefix
	engine.Get(strings.TrimPrefix("/dictionaries/:dictionary_id/items/:id", basePath), DataFunc2(controller.Show, Integer[int64]("dictionaryId", PathParamError), Integer[int64]("id", PathParamError)))
	engine.Post(strings.TrimPrefix("/dictionaries/:dictionary_id/items", basePath), Func2(controller.Create, Integer[int64]("dictionaryId", PathParamError), Body[dto.DictionaryGroupItemForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/dictionaries/:dictionary_id/items/:id", basePath), Func3(controller.Update, Integer[int64]("dictionaryId", PathParamError), Integer[int64]("id", PathParamError), Body[dto.DictionaryGroupItemForm](BodyParamError)))
	engine.Delete(strings.TrimPrefix("/dictionaries/:dictionary_id/items/:id", basePath), Func2(controller.Delete, Integer[int64]("dictionaryId", PathParamError), Integer[int64]("id", PathParamError)))
}
