// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/v1/dictionary_item.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DictionaryItemShowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Id      int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DictionaryItemShowRequest) Reset() {
	*x = DictionaryItemShowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_dictionary_item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryItemShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryItemShowRequest) ProtoMessage() {}

func (x *DictionaryItemShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dictionary_item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryItemShowRequest.ProtoReflect.Descriptor instead.
func (*DictionaryItemShowRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_dictionary_item_proto_rawDescGZIP(), []int{0}
}

func (x *DictionaryItemShowRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DictionaryItemShowRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DictionaryItemShowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Id      int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Order   int64  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *DictionaryItemShowResponse) Reset() {
	*x = DictionaryItemShowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_dictionary_item_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryItemShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryItemShowResponse) ProtoMessage() {}

func (x *DictionaryItemShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dictionary_item_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryItemShowResponse.ProtoReflect.Descriptor instead.
func (*DictionaryItemShowResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_dictionary_item_proto_rawDescGZIP(), []int{1}
}

func (x *DictionaryItemShowResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DictionaryItemShowResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DictionaryItemShowResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DictionaryItemShowResponse) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

// Create
type DictionaryItemCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Value   string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Order   int64  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *DictionaryItemCreateRequest) Reset() {
	*x = DictionaryItemCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_dictionary_item_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryItemCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryItemCreateRequest) ProtoMessage() {}

func (x *DictionaryItemCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dictionary_item_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryItemCreateRequest.ProtoReflect.Descriptor instead.
func (*DictionaryItemCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_dictionary_item_proto_rawDescGZIP(), []int{2}
}

func (x *DictionaryItemCreateRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DictionaryItemCreateRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DictionaryItemCreateRequest) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

// Update
type DictionaryItemUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Id      int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Order   int64  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *DictionaryItemUpdateRequest) Reset() {
	*x = DictionaryItemUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_dictionary_item_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryItemUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryItemUpdateRequest) ProtoMessage() {}

func (x *DictionaryItemUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dictionary_item_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryItemUpdateRequest.ProtoReflect.Descriptor instead.
func (*DictionaryItemUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_dictionary_item_proto_rawDescGZIP(), []int{3}
}

func (x *DictionaryItemUpdateRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DictionaryItemUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DictionaryItemUpdateRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DictionaryItemUpdateRequest) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

// Delete
type DictionaryItemDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Id      int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DictionaryItemDeleteRequest) Reset() {
	*x = DictionaryItemDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_dictionary_item_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryItemDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryItemDeleteRequest) ProtoMessage() {}

func (x *DictionaryItemDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dictionary_item_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryItemDeleteRequest.ProtoReflect.Descriptor instead.
func (*DictionaryItemDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_dictionary_item_proto_rawDescGZIP(), []int{4}
}

func (x *DictionaryItemDeleteRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DictionaryItemDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_v1_dictionary_item_proto protoreflect.FileDescriptor

var file_proto_v1_dictionary_item_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x19, 0x44, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x73, 0x0a, 0x1a, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65,
	0x6d, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0x64, 0x0a, 0x1b, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x74, 0x0a, 0x1b, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x22, 0x48, 0x0a, 0x1b, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x74,
	0x65, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xc5, 0x02, 0x0a, 0x15, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x04, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x23, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x68, 0x6f, 0x77, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x47, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x47, 0x0a, 0x06, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x2d, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_dictionary_item_proto_rawDescOnce sync.Once
	file_proto_v1_dictionary_item_proto_rawDescData = file_proto_v1_dictionary_item_proto_rawDesc
)

func file_proto_v1_dictionary_item_proto_rawDescGZIP() []byte {
	file_proto_v1_dictionary_item_proto_rawDescOnce.Do(func() {
		file_proto_v1_dictionary_item_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_dictionary_item_proto_rawDescData)
	})
	return file_proto_v1_dictionary_item_proto_rawDescData
}

var file_proto_v1_dictionary_item_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_dictionary_item_proto_goTypes = []interface{}{
	(*DictionaryItemShowRequest)(nil),   // 0: proto.v1.DictionaryItemShowRequest
	(*DictionaryItemShowResponse)(nil),  // 1: proto.v1.DictionaryItemShowResponse
	(*DictionaryItemCreateRequest)(nil), // 2: proto.v1.DictionaryItemCreateRequest
	(*DictionaryItemUpdateRequest)(nil), // 3: proto.v1.DictionaryItemUpdateRequest
	(*DictionaryItemDeleteRequest)(nil), // 4: proto.v1.DictionaryItemDeleteRequest
	(*emptypb.Empty)(nil),               // 5: google.protobuf.Empty
}
var file_proto_v1_dictionary_item_proto_depIdxs = []int32{
	0, // 0: proto.v1.DictionaryItemService.Show:input_type -> proto.v1.DictionaryItemShowRequest
	2, // 1: proto.v1.DictionaryItemService.Create:input_type -> proto.v1.DictionaryItemCreateRequest
	3, // 2: proto.v1.DictionaryItemService.Update:input_type -> proto.v1.DictionaryItemUpdateRequest
	4, // 3: proto.v1.DictionaryItemService.Delete:input_type -> proto.v1.DictionaryItemDeleteRequest
	1, // 4: proto.v1.DictionaryItemService.Show:output_type -> proto.v1.DictionaryItemShowResponse
	5, // 5: proto.v1.DictionaryItemService.Create:output_type -> google.protobuf.Empty
	5, // 6: proto.v1.DictionaryItemService.Update:output_type -> google.protobuf.Empty
	5, // 7: proto.v1.DictionaryItemService.Delete:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_dictionary_item_proto_init() }
func file_proto_v1_dictionary_item_proto_init() {
	if File_proto_v1_dictionary_item_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_dictionary_item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryItemShowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_dictionary_item_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryItemShowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_dictionary_item_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryItemCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_dictionary_item_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryItemUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_dictionary_item_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryItemDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_dictionary_item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_dictionary_item_proto_goTypes,
		DependencyIndexes: file_proto_v1_dictionary_item_proto_depIdxs,
		MessageInfos:      file_proto_v1_dictionary_item_proto_msgTypes,
	}.Build()
	File_proto_v1_dictionary_item_proto = out.File
	file_proto_v1_dictionary_item_proto_rawDesc = nil
	file_proto_v1_dictionary_item_proto_goTypes = nil
	file_proto_v1_dictionary_item_proto_depIdxs = nil
}
